// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh6a5cfh2wWOv1kskq3IjNidZcXbgt3cE',
    appId: '1:157176999196:web:b54808e71908d70d90ded9',
    messagingSenderId: '157176999196',
    projectId: 'touristoffice-9dbff',
    authDomain: 'touristoffice-9dbff.firebaseapp.com',
    storageBucket: 'touristoffice-9dbff.appspot.com',
    measurementId: 'G-TYH1D3LG5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3cw1j3o8VLF3o2el3dc-u5m7qwF381k',
    appId: '1:157176999196:android:d9b84d915f0f795e90ded9',
    messagingSenderId: '157176999196',
    projectId: 'touristoffice-9dbff',
    storageBucket: 'touristoffice-9dbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm7wQoGzkEroJglfN1IaWv9jJDwyBrjIE',
    appId: '1:157176999196:ios:cce4db42996ba8b190ded9',
    messagingSenderId: '157176999196',
    projectId: 'touristoffice-9dbff',
    storageBucket: 'touristoffice-9dbff.appspot.com',
    iosBundleId: 'com.example.tourist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm7wQoGzkEroJglfN1IaWv9jJDwyBrjIE',
    appId: '1:157176999196:ios:cce4db42996ba8b190ded9',
    messagingSenderId: '157176999196',
    projectId: 'touristoffice-9dbff',
    storageBucket: 'touristoffice-9dbff.appspot.com',
    iosBundleId: 'com.example.tourist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh6a5cfh2wWOv1kskq3IjNidZcXbgt3cE',
    appId: '1:157176999196:web:5c0b0d5f7bd4c75f90ded9',
    messagingSenderId: '157176999196',
    projectId: 'touristoffice-9dbff',
    authDomain: 'touristoffice-9dbff.firebaseapp.com',
    storageBucket: 'touristoffice-9dbff.appspot.com',
    measurementId: 'G-1YDKHNT8VK',
  );
}
